name: Heroku Deployment

on:
    push:
        branches: ["main"]
jobs:
    build:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
            - uses: actions/checkout@v3

            - name: Set up JDK 19
              uses: actions/setup-java@v3
              with:
                  java-version: "19"
                  distribution: "temurin"
                  cache: maven

            - name: Build with Maven
              run: mvn --batch-mode -DskipTests=true -f pom-test.xml -Dspring.profiles.active=test package

            - name: JUnit Test
              run: mvn --batch-mode -Dmaven.test.failure.ignore=true -f pom-test.xml -Dspring.profiles.active=test test

            - name: JUnit Test Report
              uses: mikepenz/action-junit-report@v3
              if: success() || failure()
              with:
                  report_paths: "**/TEST-*.xml"

            - name: Heroku GitHub Deploy
              uses: dentarg/heroku@v1.1.2
              with:
                  # The Heroku app name
                  app: geometrypuzzle
                  # Heroku API key (OAuth token)
                  key: ${{secrets.HEROKU_API_KEY}}
